1. Newspaper.objects.filter(pk=1).values('journalist')
2. Newspaper.objects.filter(journalist='Laney Mccullough').count()
3. Newspaper.objects.order_by('-pk')
4. Newspaper.objects.order_by('-created_at')
5. Newspaper.objects.filter(journalist__contains='Britney').count()
6. Newspaper.objects.filter(journalist__in=['Britney Mahoney', 'Arianna Walls', 'Carl Short']).count()
7. Newspaper.objects.filter(created_at__gte='2000-01-01').count()
8. last = Newspaper.objects.last()
print(f'title : {last.title}')
print(f'content : {last.content}')
print(f'journalist : {last.journalist}')